[template]
prefix = "crawl-enrichment-topology-_ENV_TYPE_"
src = "crawl-enrichment-topology.tmpl"
dest = "/etc/fk-3p-storm/conf/crawl-enrichment-topology.yaml"
keys = [
    "/name",
    "/workers",
    "/ackers",
    "/debug",
    "/topologyTimeoutInSecs",
    "/maxSpoutPending",
    "/topologyStatsSampleRate",
    "/pulsarTopics.centralEnrichedTopic",
    "/pulsarTopics.retryTopic",
    "/pulsarTopics.dlqTopic",
    "/retryConfig.maxAttempts",
    "/l2ClientConfig.baseUrl",
    "/l2ClientConfig.enrichPath",
    "/l2ClientConfig.connectTimeoutMs",
    "/l2ClientConfig.readTimeoutMs",
    "/l2ClientConfig.maxBatchSize",
    "/l2ClientConfig.microBatchWindowCount",
    "/l2ClientConfig.microBatchWindowSeconds",
    "/pipelineRouting.enabled",
    "/pipelineRouting.jdbcUrl",
    "/pipelineRouting.jdbcUser",
    "/pipelineRouting.jdbcPassword",
    "/pipelineRouting.refreshIntervalMinutes",
    "/pipelineRouting.sql",
    "/pulsarClientConfig.remoteEndpoint",
    "/pulsarClientConfig.statIntervalSeconds",
    "/pulsarClientConfig.clientId",
    "/pulsarClientConfig.clientSecret",
    "/pulsarClientConfig.issuerUrl",
    "/pulsarClientConfig.audience",
    "/pulsarProducerProps.bootstrap.servers",
    "/pulsarProducerProps.key.serializer",
    "/pulsarProducerProps.value.serializer",
    "/pulsarProducerProps.pulsar.block.if.producer.queue.full",
    "/pulsarProducerProps.linger.ms",
    "/pulsarProducerProps.delivery.timeout.ms",
    "/pulsarProducerProps.pulsar.authentication.class",
    "/rawPulsarSpoutConfig.name",
    "/rawPulsarSpoutConfig.parallelismHint",
    "/rawPulsarSpoutConfig.pulsarSpoutConfig.subscriptionName",
    "/rawPulsarSpoutConfig.pulsarSpoutConfig.serviceUrl",
    "/rawPulsarSpoutConfig.pulsarSpoutConfig.topic",
    "/rawPulsarSpoutConfig.consumerConfig.subscriptionType",
    "/rawPulsarSpoutConfig.consumerConfig.subscriptionInitialPosition",
    "/rawPulsarSpoutConfig.consumerConfig.topicNames0",
    "/retryPulsarSpoutConfig.name",
    "/retryPulsarSpoutConfig.parallelismHint",
    "/retryPulsarSpoutConfig.pulsarSpoutConfig.subscriptionName",
    "/retryPulsarSpoutConfig.pulsarSpoutConfig.serviceUrl",
    "/retryPulsarSpoutConfig.pulsarSpoutConfig.topic",
    "/retryPulsarSpoutConfig.consumerConfig.subscriptionType",
    "/retryPulsarSpoutConfig.consumerConfig.subscriptionInitialPosition",
    "/retryPulsarSpoutConfig.consumerConfig.topicNames0",
    "/pulsarDlqConfig.topic",
    "/pulsarDlqConfig.maxRedeliverCount",
    "/asyncEnrichmentBoltConfig.name",
    "/asyncEnrichmentBoltConfig.parallelismHint",
    "/centralPublisherBoltConfig.name",
    "/centralPublisherBoltConfig.parallelismHint",
    "/retryBoltConfig.name",
    "/retryBoltConfig.parallelismHint",
    "/dlqBoltConfig.name",
    "/dlqBoltConfig.parallelismHint"
]
